version: '3.7'

secrets:
  secret_key:
    external: true
  access_key:
    external: true

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-01-08T03-11-54Z
  command: server --console-address ":9001" /minio_data1
  secrets:
    - access_key
    - secret_key
  environment:
    MINIO_ACCESS_KEY_FILE: /run/secrets/access_key
    MINIO_SECRET_KEY_FILE: /run/secrets/secret_key
  # healthcheck:
  #   test: ['CMD', 'curl', '-f', 'http://localhost:13338/minio/health/live']
  #   interval: 30s
  #   timeout: 20s
  #   retries: 3

services:
  minio:
    <<: *minio-common
    hostname: minio
    volumes:
      - minio_data1_1:/minio_data1
      - minio_data1_2:/minio_data2

  nginx:
    image: nginx:1.21.5-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '13337:9000'
      - '13338:9001'
    depends_on:
      - minio

volumes:
  minio_data1_1:
  minio_data1_2:
